language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libeigen3-dev libboost-dev python-numpy

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make check
